name: crucible-ci

on:
  # run pull request events for the master branch only
  # ignore pull requests that only change documentation/license files
  pull_request:
    branches: [ master ]
    paths-ignore:
      - LICENSE
      - '*.md'

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci-iteration-repeat-runs-oslat:
    runs-on: [self-hosted, cpu-partitioning, remotehost]

    steps:
    - name: Checkout crucible
      uses: actions/checkout@v2
      with:
        path: crucible

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "oslat"
        ci_target: "crucible"
        ci_target_dir: ${{ github.workspace }}/crucible
        repeat_runs: "yes"
        scenarios: "oslat"

  crucible-ci-iteration-repeat-runs-fio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout crucible
      uses: actions/checkout@v2
      with:
        path: crucible

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "fio"
        ci_target: "crucible"
        ci_target_dir: ${{ github.workspace }}/crucible
        repeat_runs: "yes"
        scenarios: "fio"

  crucible-ci-iteration-repeat-runs-uperf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout crucible
      uses: actions/checkout@v2
      with:
        path: crucible

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "uperf"
        ci_target: "crucible"
        ci_target_dir: ${{ github.workspace }}/crucible
        repeat_runs: "yes"
        scenarios: "uperf"

  crucible-ci-iteration-repeat-runs-iperf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout crucible
      uses: actions/checkout@v2
      with:
        path: crucible

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "iperf"
        ci_target: "crucible"
        ci_target_dir: ${{ github.workspace }}/crucible
        repeat_runs: "yes"
        scenarios: "iperf"
