# as described here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

# Basic ci workflow using github actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the master branch
  # only for pull requests that only change documentation/license files
  pull_request:
    branches: [ master ]
    paths:
      - LICENSE
      - '**.md'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - .github/workflows/faux-ci.yaml
      - .github/workflows/crucible-release.yaml
      - 'docs/**'
      - 'spec/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to test installation
  install:
    # Job will run on github-hosted runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: 'echo "No build required" '
